from django.contrib import admin

from .models import *

admin.site.register(FormOfTheCabin)
admin.site.register(TypeOfCabin)
admin.site.register(BankDetail)
admin.site.register(DetailsOfTheOrganization)
admin.site.register(OrganizationValidityPeriod)
admin.site.register(BankDetailValidityPeriod)
admin.site.register(DetailsOfTheOrganizationValidityPeriod)
admin.site.register(OrganizationAddressValidityPeriod)
admin.site.register(ForestryValidityPeriod)
admin.site.register(DepartmentAddressValidityPeriod)
admin.site.register(OrganizationAddress)
admin.site.register(TreeSpecies)
admin.site.register(LocalityType)
admin.site.register(Organization)
admin.site.register(Forestry)
admin.site.register(DepartmentAddress)
admin.site.register(RepresentativeOfTheDepartmentAtValidityPeriod)
admin.site.register(RepresentativeOfTheDepartmentAt)
admin.site.register(Position)
admin.site.register(PowerOfAttorneyOfTheRepresentativeValidityPeriod)
admin.site.register(PowerOfAttorneyOfTheRepresentative)
admin.site.register(DistrictForestry)
admin.site.register(Tract)
admin.site.register(Quarter)
admin.site.register(Plot)
admin.site.register(PlotWoodSpecies)
admin.site.register(HeatedPremise)
admin.site.register(PersonResidenceAddress)
admin.site.register(RepresentativeResidenceAddress)
admin.site.register(PersonPassport)
admin.site.register(RepresentativePassport)
admin.site.register(Person)
admin.site.register(RepresentativePerson)
admin.site.register(Statement)
admin.site.register(Contract)
